export type ScaffoldFile = {
  path: string;
  content: string;
};

const PACKAGE_JSON = `{
  "name": "refineai-preview-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3001",
    "build": "next build",
    "start": "next start -p 3001",
    "lint": "next lint"
  },
  "dependencies": {
    "@supabase/supabase-js": "^2.108.2",
    "next": "14.2.35",
    "openai": "^4.104.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@types/node": "^20.17.0",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "autoprefixer": "^10.4.20",
    "eslint": "^8.57.1",
    "eslint-config-next": "14.2.35",
    "postcss": "^8.4.49",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.7.2"
  }
}
`;

const TSCONFIG = `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;
`;

const TAILWIND_CONFIG = `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: { extend: {} },
  plugins: [],
};
export default config;
`;

const POSTCSS_CONFIG = `/** @type {import('postcss-load-config').Config} */
const config = { plugins: { tailwindcss: {}, autoprefixer: {} } };
export default config;
`;

const LAYOUT = `import "./globals.css";

export const metadata = {
  title: "Preview App",
  description: "Generated by RefineAI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

const GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: system-ui, sans-serif;
}
`;

const PAGE = `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
      <h1 className="text-2xl font-bold">Preview App</h1>
      <p className="mt-2 text-gray-600">Your generated app will appear here.</p>
    </main>
  );
}
`;

export const SCAFFOLD_FILES: ScaffoldFile[] = [
  { path: "package.json", content: PACKAGE_JSON },
  { path: "tsconfig.json", content: TSCONFIG },
  { path: "next.config.mjs", content: NEXT_CONFIG },
  { path: "tailwind.config.ts", content: TAILWIND_CONFIG },
  { path: "postcss.config.mjs", content: POSTCSS_CONFIG },
  { path: "app/layout.tsx", content: LAYOUT },
  { path: "app/globals.css", content: GLOBALS_CSS },
  { path: "app/page.tsx", content: PAGE },
];

export function getMissingScaffold(existingPaths: Set<string>): ScaffoldFile[] {
  return SCAFFOLD_FILES.filter((f) => !existingPaths.has(f.path.replace(/\\/g, "/")));
}

export function mergePackageJson(existingContent: string | null): string {
  if (!existingContent) return PACKAGE_JSON;
  try {
    const existing = JSON.parse(existingContent) as Record<string, unknown>;
    const scaffold = JSON.parse(PACKAGE_JSON) as Record<string, unknown>;
    return JSON.stringify(
      {
        ...scaffold,
        ...existing,
        scripts: { ...(scaffold.scripts as object), ...(existing.scripts as object), dev: "next dev -p 3001" },
        dependencies: { ...(scaffold.dependencies as object), ...(existing.dependencies as object) },
        devDependencies: {
          ...(scaffold.devDependencies as object),
          ...(existing.devDependencies as object),
        },
      },
      null,
      2
    );
  } catch {
    return PACKAGE_JSON;
  }
}
