-- Developer mode columns for sessions
ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS model TEXT DEFAULT 'gpt-4o',
  ADD COLUMN IF NOT EXISTS temperature REAL DEFAULT 0.7,
  ADD COLUMN IF NOT EXISTS score_threshold INTEGER DEFAULT 90,
  ADD COLUMN IF NOT EXISTS max_rounds INTEGER DEFAULT 12,
  ADD COLUMN IF NOT EXISTS system_prompt TEXT,
  ADD COLUMN IF NOT EXISTS json_mode BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS tokens_used INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS time_taken REAL DEFAULT 0;
